const localEngravingIcons = {
  원한: '/images/engravings/Buff_71.png',
  구슬동자: '/images/engravings/Buff_18.png',
  '질량 증가': '/images/engravings/Ability_231.png',
  '타격의 대가': '/images/engravings/Ability_233.png',
  '마나의 흐름': '/images/engravings/Buff_63.png',
  '저주받은 인형': '/images/engravings/Buff_237.png',
  '예리한 둔기': '/images/engravings/achieve_03_40.png',
  '돌격 대장': '/images/engravings/Buff_210.png',
  각성: '/images/engravings/Buff_113.png',
  '결투의 대가': '/images/engravings/Ability_224.png',
  '기습의 대가': '/images/engravings/Buff_148.png',
  아드레날린: '/images/engravings/Ability_235.png',
  전문의: '/images/engravings/Ability_237.png',
  '분쇄의 주먹': '/images/engravings/Buff_83.png',
  '안정된 상태': '/images/engravings/Buff_105.png',
  '탈출의 명수': '/images/engravings/Buff_10.png',
  '실드 관통': '/images/engravings/Buff_89.png',
  '폭발물 전문가': '/images/engravings/Buff_121.png',
  '번개의 분노': '/images/engravings/Buff_191.png',
  '중갑 착용': '/images/engravings/Buff_46.png',
  '시선 집중': '/images/engravings/Ability_234.png',
  '에테르 포식자': '/images/engravings/Buff_74.png',
  '정기 흡수': '/images/engravings/Buff_65.png',
  '굳은 의지': '/images/engravings/Buff_44.png',
  '마나 효율 증가': '/images/engravings/Buff_166.png',
  '달인의 저력': '/images/engravings/Buff_147.png',
  '여신의 가호': '/images/engravings/Buff_229.png',
  '강화 방패': '/images/engravings/Buff_239.png',
  '부러진 뼈': '/images/engravings/Buff_94.png',
  '최대 마나 증가': '/images/engravings/Buff_122.png',
  불굴: '/images/engravings/Buff_66.png',
  강령술: '/images/engravings/Buff_29.png',
  바리게이트: '/images/engravings/Buff_170.png',
  승부사: '/images/engravings/Buff_136.png',
  '정밀 단도': '/images/engravings/Ability_239.png',
  '속전 속결': '/images/engravings/Ability_236.png',
  '긴급 구조': '/images/engravings/Ability_238.png',
  추진력: '/images/engravings/Ability_232.png',
  '위기 모면': '/images/engravings/Buff_162.png',
  '급소 타격': '/images/engravings/Buff_168.png',
  '약자 무시': '/images/engravings/achieve_04_30.png',
  '슈퍼 차지': '/images/engravings/achieve_06_14.png',
  선수필승: '/images/engravings/achieve_08_62.png',
}

export function getEngravingIcon(name, fallback = '') {
  const engravingName = String(name || '').replace(/\s/g, '')
  const matchedName = Object.keys(localEngravingIcons).find(key => engravingName.includes(key.replace(/\s/g, '')))
  return matchedName ? localEngravingIcons[matchedName] : fallback
}
